# Generated by Django 4.1.3 on 2022-11-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_booking_endtime_alter_service_time_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='endtime',
            field=models.TimeField(editable=False, null=True),
        ),
    ]
