# Generated by Django 4.1.3 on 2022-11-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_service_time_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='endtime',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='time_required',
            field=models.IntegerField(),
        ),
    ]
